custom_config_form.admin_settings_form:
  path: '/admin/config/location_time/adminsettings'
  defaults:
    _title: 'Site Location And Timezone Form'
    _form: '\Drupal\custom_config_form\Form\LocationAndTimeConfigForm'
  requirements:
    _permission: 'access administration pages'
