custom_config_form.admin_settings_form:
  title: 'Site Location/Time Settings'
  description: 'adding location and timezone for site'
  parent: system.admin_config_system
  route_name: custom_config_form.admin_settings_form
  weight: 99
